export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';
export const LOAD_ACCORDION_MENU_INF_SUCCESS= 'LOAD_ACCORDION_MENU_INF_SUCCESS';
export const LOAD_ACCORDION_MENU_INF_REQUEST= 'LOAD_ACCORDION_MENU_INF_REQUEST';
export const LOAD_LEARNING_TEXT_SUCCESS= 'LOAD_LEARNING_TEXT_SUCCESS';
export const LOAD_LEARNING_TEXT_REQUEST= 'LOAD_LEARNING_TEXT_REQUEST';
export const LOAD_ARTICLES_SUCCESS= 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_REQUEST= 'LOAD_ARTICLES_REQUEST';